### PR TITLE
Documentation for The new Google Cloud functionality

### PR DESCRIPTION
**Pull request by TamerShlash**
This Pull Request includes in-code documentation for the 4 steps that have been created to implement the new mechanism of inserting to Google BigQuery. It also includes some code refactoring and enhancements on these steps.

### CODE REVIEW

**Comment by jorinvo** [comment]
awesome @TamerShlash :+1:

**Comment by T-Dnzt** [comment]
Looks good! :+1:

**Comment by sjfbo** [comment]
Yay, thanks it will definitely help me to catch up on what you did during my absence.
Great job!

**Comment by Anumodana** [comment]
:+1:

**Pull request merged**
