### PR TITLE
Make Pipeline #start and #join chainable

### PR DESCRIPTION
**Pull request by jorin-vogel**
See https://github.com/pocket-playlab/optimus-prime/issues/81.

### CODE REVIEW

**Comment by Anumodana** [comment]
:+1:

**Comment by TamerShlash** [comment]
:+1:

**Comment by jorin-vogel** [comment]
If anyone wants, you can update your testfiles or other places you use pipelines to the chainable way.

**Comment by jorin-vogel** [comment]
@omarkhan Can I merge this?

**Comment by T-Dnzt** [comment]
Why not make a new method that combines `start` and `wait` instead of making them chainable? With a great generic name like, you know, `run` or `execute` :smiling_imp: Looks good anyway :+1:

**Comment by jorin-vogel** [comment]
@T-Dnzt I also think we could simplify the standard use case. But could do this in the future in another PR :wink:

**Pull request merged**
