### PR TITLE
Thor-based CLI and Factories

### PR DESCRIPTION
**Pull request by TamerShlash**
### New CLI

The new OptimusPrime CLI is based on [Thor](https://github.com/erikhuda/thor), it gives cleaner command line interface and better error and help messages.

* To get help about the available commands, run `bundle exec optimus` without any arguments.
* To learn more about a specific command and learn about it's sub-commands,  run `bundle exec optimus COMMAND_NAME` without any arguments.

### Factory

A factory is a config file that has a list of pipelines which will be run **sequentially**.
* Each pipeline is identified by an `id`, and is specified by a file and a pipeline name inside that file.
* Each pipeline can have `pre_wait` option, which will make the factory sleep before starting this pipeline, and `post_wait` option, which will make the factory sleep after finishing this pipeline (regardless of the finish status).
* Each pipeline can also depend on other pipelines (using their `ids`); if any of the dependencies finished with an exit code other than 0, this pipeline will not be run.

### Tests

The included tests are quick and dirty solution (but they still work), they only test the output of the commands, which is not a good thing.

### Future Plans
* Improving tests to become more reliable, notes about that are included in the binary spec file.
* Implement a `generator` command that generates config files, which will make it a lot easier and reliable for people to make new config files.

### CODE REVIEW

**Comment by omarkhan** [comment]
Looks good @TamerShlash! :+1:

**Comment by Anumodana** [comment]
Great! :+1:

**Comment by T-Dnzt** [comment]
Awesome! :+1:

**Comment by jorin-vogel** [comment]
Looks really good :+1: 
@TamerShlash Do you think it would be possible to add a little paragraph to the readme explaining how to use the tool (and mention that it exists in the first place)?
Would be really helpful :wink:

**Comment by TamerShlash** [comment]
@jorin-vogel Sure, we _need_ to do that actually :smiley:

**Comment by TamerShlash** [comment]
@jorin-vogel I will postpone the README update, as there's a lot of things to do for it.

**Pull request merged**
