### PR TITLE
Handle Sequel Database connection error

### PR DESCRIPTION
**Pull request by T-Dnzt**
This PR adds a way to handle `Sequel::DatabaseConnectionError` and retries until the connection to the DB works.

### CODE REVIEW

**Comment by jorin-vogel** [comment]
:+1: 
This only handles error while deletion though.. The actual writing (in RdbmsWriter) can still fail, right?

And should we set something like a max_retries value that it doesn't get stuck?

**Comment by T-Dnzt** [comment]
@jorin-vogel Yeah you're right for the first part, I'll change that. For the `max_retries`, I actually started with it and I finally removed it :smiling_imp: Alright, I'll put it back!

**Comment by jorin-vogel** [comment]
@T-Dnzt nice work! Looks good to me!
Exactly what I imagined :wink: 
This way I don't even have to add this feature to RdbmsDynamic. It should just work :tm:.

**Comment by simonbnrd** [comment]
Great :+1:

**Comment by iammchat** [comment]
:+1:

**Comment by Anumodana** [comment]
:smiley: :+1:

**Pull request merged**
