### PR TITLE
Error alerts

### PR DESCRIPTION
**Pull request by T-Dnzt**
This Pull Request adds a way to handle exceptions with external services. For now, it only supports `Sentry` but adding more adapters is easy. 

The config inside a pipeline looks like this:

```
errors:
  adapter: Sentry
  options:
    dsn: 'your_dsn_url'
```

All the `options` will be passed to the configuration block of the exception handling gem. In Sentry case, it's [sentry-raven](https://github.com/getsentry/raven-ruby).

### CODE REVIEW

**Comment by sjfbo** [comment]
:+1:  lgtm

**Comment by omarkhan** [comment]
:+1:

**Comment by iammchat** [comment]
:+1:

**Comment by Anumodana** [comment]
:+1:

**Pull request merged**
