### PR TITLE
Add contained to RecordFilter

### PR DESCRIPTION
**Pull request by iammchat**
**PR** : This PR adds the `stringify` option to `RecordFilter` in order to match string records. It also add  new filters to the `RecordFilter` transformer.

`contained` : accepts the record if it contains any of the specified values
`not_contained` : accepts the record if it contains none of the specified values

**Warning** : Before I can merge this PR to master, I need to know if any of your pipelines is using symbolized records because it will now look for strings by default. Let me know so we can plan accordingly.

### CODE REVIEW

**Comment by omarkhan** [comment]
About strings vs symbols as hash keys: can we just [`HashWithIndifferentAccess`](http://api.rubyonrails.org/classes/ActiveSupport/HashWithIndifferentAccess.html) for all data going through the pipeline? @T-Dnzt @TamerShlash @Anumodana @jorin-vogel

**Comment by TamerShlash** [comment]
@omarkhan We discussed that and decided to do the quickest possible solution for now, that's why we ended up adding `stringify`.

But as I can see we are increasingly adding stuff that already exist in `ActiveSupport` (see core_ext), so I think we should use it instead of copying portions.

The only thing we still worried about is that HashWithIndifferenctAccess could break something in other included libraries, but I think it will not because it doesn't take effect unless explicitly called.

**Comment by jorin-vogel** [comment]
I also think it might be helpful to use `ActiveSupport` if it is not too complicated. 
I would also like to use `String#tableize` for the RdbmsDynamic destionation I'm building and I guess we find more usecases over time.

**Comment by omarkhan** [comment]
Let's get this merged so that we can merge https://github.com/pocket-playlab/analytics/pull/29. I'm in favour of adding ActiveSupport and using `HashWithIndifferentAccess` everywhere.

**Comment by TamerShlash** [comment]
@omarkhan I will work on adding `ActiveSupport`.

**Pull request merged**
