### PR TITLE
Fix bug in schema rebuilding mechanism

### PR DESCRIPTION
**Pull request by TamerShlash**
The `fields` method in `bigquery_table_base` is caching schema fields, and consequently duplicate fields were being added to the schema every time, which ultimately results in an error when trying to update the table schema.
Reimplementing the method in `bigquery_dynamic` so that it doesn't cache fields solves the problem.

### CODE REVIEW

**Comment by Anumodana** [comment]
Could you please add a description to describe about the bug and solution?

**Comment by TamerShlash** [comment]
@Anumodana updated, thanks for the note :+1:

**Comment by Anumodana** [comment]
It looks good.

**Comment by T-Dnzt** [comment]
:+1:

**Pull request merged**
