### PR TITLE
Use Ruby 2.2.1

### PR DESCRIPTION
**Pull request by simonbnrd**
Currently the latest Ruby version from brightbox ppa repository is now the 2.2.1 and it doesn't match anymore the fixed version in the Gemfile (2.2.0) of the project. Because of that the vbox's provisioning was broken.

```
$ vagrant provision
==> default: Running provisioner: shell...
    default: Running: /var/folders/nx/_sgp_sy13dq0nh2h7g_2j87m0000gp/T/vagrant-shell20150409-25197-1mok69k.sh
==> default: gpg:
==> default: keyring `/tmp/tmpj_4ngfkv/secring.gpg' created
==> default: gpg:
==> default: keyring `/tmp/tmpj_4ngfkv/pubring.gpg' created
==> default: gpg:
==> default: requesting key C3173AA6 from hkp server keyserver.ubuntu.com
==> default: gpg: /tmp/tmpj_4ngfkv/trustdb.gpg: trustdb created
==> default: gpg: key C3173AA6: public key "Launchpad PPA for Brightbox" imported
==> default: gpg: Total number processed: 1
==> default: gpg:               imported: 1  (RSA: 1)
==> default: OK
==> default: Ign http://ppa.launchpad.net trusty InRelease
==> default: Hit http://ppa.launchpad.net trusty Release.gpg
==> default: Hit http://ppa.launchpad.net trusty Release
==> default: Hit http://ppa.launchpad.net trusty/main amd64 Packages
==> default: Hit http://ppa.launchpad.net trusty/main Translation-en
==> default: Ign http://security.ubuntu.com trusty-security InRelease
==> default: Hit http://security.ubuntu.com trusty-security Release.gpg
==> default: Hit http://security.ubuntu.com trusty-security Release
==> default: Hit http://security.ubuntu.com trusty-security/main Sources
==> default: Ign http://archive.ubuntu.com trusty InRelease
==> default: Ign http://archive.ubuntu.com trusty-updates InRelease
==> default: Hit http://archive.ubuntu.com trusty Release.gpg
==> default: Hit http://archive.ubuntu.com trusty-updates Release.gpg
==> default: Hit http://archive.ubuntu.com trusty Release
==> default: Hit http://archive.ubuntu.com trusty-updates Release
==> default: Hit http://archive.ubuntu.com trusty/main Sources
==> default: Hit http://archive.ubuntu.com trusty/universe Sources
==> default: Hit http://archive.ubuntu.com trusty/main amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/universe amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/main Translation-en
==> default: Hit http://archive.ubuntu.com trusty/universe Translation-en
==> default: Hit http://archive.ubuntu.com trusty-updates/main Sources
==> default: Hit http://archive.ubuntu.com trusty-updates/universe Sources
==> default: Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
==> default: Hit http://security.ubuntu.com trusty-security/universe Sources
==> default: Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-updates/main Translation-en
==> default: Hit http://archive.ubuntu.com trusty-updates/universe Translation-en
==> default: Ign http://archive.ubuntu.com trusty/main Translation-en_US
==> default: Ign http://archive.ubuntu.com trusty/universe Translation-en_US
==> default: Hit http://security.ubuntu.com trusty-security/main amd64 Packages
==> default: Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
==> default: Hit http://security.ubuntu.com trusty-security/main Translation-en
==> default: Hit http://security.ubuntu.com trusty-security/universe Translation-en
==> default: Reading package lists...
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: cmake is already the newest version.
==> default: libsqlite3-dev is already the newest version.
==> default: pkg-config is already the newest version.
==> default: git is already the newest version.
==> default: ruby2.2 is already the newest version.
==> default: ruby2.2-dev is already the newest version.
==> default: 0 upgraded, 0 newly installed, 0 to remove and 18 not upgraded.
==> default: Successfully installed bundler-1.9.2
==> default: Parsing documentation for bundler-1.9.2
==> default: Done installing documentation for bundler after 3 seconds
==> default: 1 gem installed
==> default: Your Ruby version is 2.2.1, but your Gemfile specified 2.2.0
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
FAIL: 1
```

EDIT:
Instead of using RVM to use a fixed version of Ruby, following the comment of @omarkhan I'll Dockerize the thing ASAP in order to keep the control on which Ruby version we use like @TamerShlash and @MacTynow also asked for in the comments of this PR.

### CODE REVIEW

**Comment by jorin-vogel** [comment]
:+1: I ran into the same issue.

**Comment by TamerShlash** [comment]
I would suggest specifying the version installed in Vagrant as well. We should control which Ruby version is used, and update it both in Vagrant and in the Gemfile when we really want to upgrade, not when there's a new version out there.

**Comment by jorin-vogel** [comment]
:+1: @TamerShlash

**Comment by MacTynow** [comment]
@TamerShlash is right. You can't change a software running in production just because there is a new version out.

**Comment by simonbnrd** [comment]
I'll update it and use rvm.

**Comment by simonbnrd** [comment]
@TamerShlash @MacTynow done

**Comment by omarkhan** [comment]
Please can we stick with the brighbox ppa for now? rvm builds ruby from source, which takes *forever*. If we're going to fix this for real, let's dockerize it and use compose.

**Comment by simonbnrd** [comment]
Alright, let's switch back to brighbox ppa and I'll dockerize the thing after.

**Comment by omarkhan** [comment]
:+1:

**Comment by jorin-vogel** [comment]
Doesn't brighbox ppa allow us to specify a more specific version?

**Comment by omarkhan** [comment]
It should be possible to install an older version if it's still in the
archive

**Comment by simonbnrd** [comment]
I think it's interesting to switch to 2.2.1 version since they've fixed some stuff like memory leak issues with symbols GC. I guess we don't really have restrictions for now in this project that prevent us to move forward and upgrade the version we use.

**Comment by simonbnrd** [comment]
The following is pointless now since we're about to switch on Docker.

**Pull request closed without merging**
