### PR TITLE
Replace CastString transform with generic CastType transform

### PR DESCRIPTION
**Pull request by omarkhan**
This pull request replaces `CastString` with a `CastType` transform that allows any type to be converted, not just strings.

### CODE REVIEW

**Comment by jorin-vogel** [comment]
@omarkhan We would have to update all pipelines using CastString for this.
Is it possible to just add CastType as new transformer instead of overwriting?

**Comment by omarkhan** [comment]
@jorin-vogel that would introduce a lot of duplication. I will update the pipelines and make a pull request. Should be a simple find-and-replace job

**Comment by jorin-vogel** [comment]
Ok, cool!

**Comment by omarkhan** [comment]
@Anumodana @T-Dnzt @TamerShlash @iammchat @simonbnrd anyone object to this?

**Comment by T-Dnzt** [comment]
@omarkhan No objection, looks good, just have to update all the pipelines. :smiling_imp:

**Pull request merged**
