### PR TITLE
Make BigQuery source to support multiple sql queries

### PR DESCRIPTION
**Pull request by Anumodana**
#### Problem
BigQuery source just support only a sql query at a time. This means that if we want to run 100 queries at once, BigQuery source must be initialized 100 times.

#### Solution
Make BigQuery source support multiple sql queries.

### CODE REVIEW

**Comment by omarkhan** [comment]
@Anumodana 

1. What's wrong with creating lots of bigquery sources and running them in parallel?
2. If the results from lots of different queries come from the same source, does that mean the next step in the pipeline has to handle many different kinds of input?

**Comment by Anumodana** [comment]
@omarkhan We have to specify the pipeline before we start it. Currently, we have about 50 sql queries that we need to run and the result of each query must be merged together (transform) before they have been inserted into the database. Is there any way to merge the results together before they're inserted into the database if BigQuery still supports only one sql query?

**Comment by omarkhan** [comment]
We can just put all 50 sources in the pipeline, and send their output to the same transform step. The end result is the same, except that the queries are run in parallel (so faster)

**Comment by Anumodana** [comment]
@omarkhan ok

**Pull request closed without merging**
