### PR TITLE
added MIT license

### PR DESCRIPTION
**Pull request by jorin-vogel**
Hope the copyright statement is correct.

### CODE REVIEW

**Comment by omarkhan** [comment]
:+1:

**Comment by rickapichairuk** [comment]
Do not merge this until we remove all proprietary code.

**Comment by omarkhan** [comment]
What proprietary code?

**Comment by T-Dnzt** [comment]
:+1:

**Comment by TamerShlash** [comment]
:+1:

**Comment by TamerShlash** [comment]
:+1: don't forget adding section about the license to REAME.md

**Comment by omarkhan** [comment]
Doesn't need to be in the README, LICENCE file is enough

**Comment by jorin-vogel** [comment]
But doesn't hurt either right :wink: ?

**Comment by TamerShlash** [comment]
Yeah just a quick reference like [https://github.com/backup/backup](here). Besides, the License file doesn't clearly says its MIT license :D

**Comment by jorin-vogel** [comment]
I'll close this branch for now and add it to master as soon as everything else is read.

**Pull request closed without merging**
